name: ppo-and-friends

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_gym:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        sudo apt install libopenmpi-dev
        pip3 install --upgrade pip
        pip3 install setuptools==65.5.0
        pip3 install pytest
        pip3 install .[gym]

    - name: Test with pytest
      run: |
        cd test
        pytest tests/train/test_gym.py

  test_gymnasium:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        sudo apt install libopenmpi-dev
        pip3 install --upgrade pip
        pip3 install setuptools==65.5.0
        pip3 install pytest
        pip3 install .[gymnasium]

    - name: Test with pytest
      run: |
        python3 -m pip install .[gymnasium]
        cd test
        pytest tests/train/ -k "gymnasium"

  test_pettingzoo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        sudo apt install libopenmpi-dev
        pip3 install --upgrade pip
        pip3 install setuptools==65.5.0
        pip3 install pytest
        pip3 install .[gymnasium]

    - name: Test with pytest
      run: |
        cd test
        pytest tests/train/ -k "zoo or mixed_actions"

  test_abmarl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        sudo apt install libopenmpi-dev
        pip3 install --upgrade pip
        pip3 install setuptools==65.5.0
        pip3 install pytest
        pip3 install .[abmarl]

    - name: Test with pytest
      run: |
        cd test
        pytest tests/train/test_abmarl.py
