name: ppo-and-friends

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade pip
        sudo apt install libopenmpi-dev
        python -m pip install pytest
        python -m pip install .
        #
        # TODO: the current release of abmarl is incompatible with
        # python3.8, but this issue is fixed in main. Abmarl also
        # depends on an older version of gym that is causing issues with
        # pip in Github's CI.
        #
        #git clone https://github.com/LLNL/Abmarl.git
        #cd Abmarl
        #pip install -r requirements.txt
        #pip install .
        #cd ../
    - name: Test with pytest
      run: |
        cd test
        pytest tests

